Repository nrfconnect/sdk-mcuboot, pull requests merged in 2024-10, with the labels that each got.

#359 [nrf noup] zephyr: Fix compressed chunk size mismatch
  boot/zephyr/Kconfig
Labels: backport-v2.8-branch

#366 [nrf noup] zephyr: Fix issues with ARM thumb decompression
  boot/zephyr/decompression.c
Labels: backport-v2.1.0-ncs2-branch

#368 [nrf noup] zephyr: Fix issues with compression TLVs
  boot/zephyr/decompression.c
Labels: backport v2.1.0-ncs2-branch

#369 [Backport v2.1.0-ncs2-branch] [nrf noup] zephyr: Fix issues with compression TLVs
  boot/zephyr/decompression.c
Labels: Backport
