Repository nrfconnect/sdk-mcuboot, pull requests merged in 2025-04, with the labels that each got.

#303 boot/zephyr/nrf_cleanup: cleanup uarte pins
  boot/zephyr/nrf_cleanup.c
Labels: bugfix

#412 [nrf fromlist] boot: zephyr: flash_map_extended: Add pointless workar…
  boot/zephyr/flash_map_extended.c
Labels: backport v2.1.0-ncs5-branch

#414 [Backport v2.1.0-ncs5-branch] [nrf fromlist] boot: zephyr: flash_map_extended: Add pointless workar…
  boot/zephyr/flash_map_extended.c
Labels: Backport

#411 [nrf noup] boot/zephyr/Kconfig: fix MBEDTLS_CFG_FILE value
  boot/zephyr/Kconfig
Labels: DNM

#415 [nrf fromlist] zephyr: Disable SPI_NOR by default for nrf7002dk/nrf5340/c…
  boot/zephyr/boards/nrf7002dk_nrf5340_cpuapp.conf
Labels: backport v2.1.0-ncs5-branch

#416 [nrf noup] boot/zephyr/Kconfig: fix MBEDTLS_CFG_FILE value
  boot/zephyr/Kconfig
Labels: bugfix, Backport

#420 [nrf noup] zephyr: Fix issue with unpadded encrypted updates
  boot/zephyr/decompression.c
Labels: backport v2.1.0-ncs5-branch

#421 [Backport v2.1.0-ncs5-branch] [nrf noup] zephyr: Fix issue with unpadded encrypted updates
  boot/zephyr/decompression.c
Labels: Backport
